### ISSUE TITLE
Allow the watch dir to be passed on cli

### ISSUE THREAD

**Issue by bvierra** [archean-cookbook/archbelt#13]
I run Archean in Windows... however I do all my development through WSL2. Since WSL allows you to access the host systems (windows) drives under /mnt/<driveletter>/ it would be nice to be able to pass the blueprint dir directly to archbelt since it cannot detect the steam library. Currently I get the following:

```bash
$ archbelt watch
Blueprint not found, or no blueprint specified, defaulting to watching all blueprints
thread 'main' panicked at src/command/mod.rs:44:44:
could not find a steam library: InvalidSteamDir(ValidationError { inner: MissingDirectory })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I could do: `archbelt watch --blueprint-dir "/mnt/e/Games/Steam/steamapps/common/Archean/Archean-data/client/blueprints/"` it would be really nice :)

**Comment by tsal** [comment]
I've got this prototyped in the `development` branch; you can `cargo install` it from the git URL and branch until I finish up the next release.  My windows machine doesn't have WSL2 setup at the moment to test this, so I'm not 100% sure it will work, but it should.. ?

I'll close this when the next development increment gets merged and released.

**Comment by tsal** [comment]
note the option comes before the subcommand, and will apply to all commands that look at the blueprint path.

e.g. `archbelt --blueprint-path /home/archean/server/Archean-data watch` 

```
❯ archbelt --help
A tool to work with Archean blueprints and XenonCode modules

Usage: archbelt [OPTIONS] [COMMAND]

Commands:
  yank      Yank code files from a blueprint
  watch     watch for changes to blueprint file(s); will yank on change as if -f is set
  complete  Generate shell completion for zsh & bash
  help      Print this message or the help of the given subcommand(s)

Options:
      --blueprint-path <PATH>  override path to blueprint files
  -h, --help                   Print help
  -V, --version                Print version
```

**Comment by tsal** [comment]
~~... just realized it's actually the game path, since the rest of the path is assembled from there, so use the archean game root as that path for now, I'll get it updated tomorrow when I'm at the windows machine again.  are you tied to it being an option to set the blueprint path? my brain went right to the game root path because I have plans to look at other features beyond the blueprints at some point.~~

**Comment by tsal** [comment]
This is what is in `development` now, and is the planned usage - if anything seems unwieldy, let me know.

note you don't need to provide both game-path and blueprint-path, one is just a subset of the other and either will work for your purposes... I think?

```
❯ archbelt --help
A tool to work with Archean blueprints and XenonCode modules

Usage: archbelt [OPTIONS] [COMMAND]

Commands:
  yank      Yank code files from a blueprint
  watch     watch for changes to blueprint file(s); will yank on change as if -f is set
  complete  Generate shell completion for zsh & bash
  help      Print this message or the help of the given subcommand(s)

Options:
      --game-path <PATH>  override path to game root
  -h, --help              Print help
  -V, --version           Print version
❯ archbelt watch --help
watch for changes to blueprint file(s); will yank on change as if -f is set

Usage: archbelt watch [OPTIONS] [TARGET]...

Arguments:
  [TARGET]...  target blueprint name (if none given, watches all)

Options:
      --blueprint-path <PATH>  path to blueprints folder
  -x, --no-collate             do not collate the files by component (use at own risk; this can get very messy..)
  -h, --help                   Print help
```

**Comment by tsal** [comment]
this was slightly-less simple to implement as I originally thought for the game path, so I've removed that for now; I'll stop posting here and instead you can keep track of #14

**Comment by bvierra** [comment]
I see you are messing with it so I figured I would try it (very little rust experience so I saw it in commands and figured what the hell). It doesn't error but doesn't see any blueprints. I tried both the Archean main dir and the blueprints sub dir:

`./target/debug/archbelt watch --blueprint-path /mnt/e/Games/Steam/steamapps/common/Archean/`

```
Blueprint not found, or no blueprint specified, defaulting to watching all blueprints
waiting for blueprint events
```

`./target/debug/archbelt watch --blueprint-path /mnt/e/Games/Steam/steamapps/common/Archean/Archean-data/client/blueprints/`

```
Blueprint not found, or no blueprint specified, defaulting to watching all blueprints
waiting for blueprint events
```

It doesn't bother me how you want the arg to be passed, as long as it works :)

**Comment by tsal** [comment]
so the watch command waits for a blueprint to be saved in-game, maybe that's a documentation problem or an implementation problem (or both!).. or it's the mount point masking the filesystem update? I would expect WSL to pass the kernel notice down to user land in linux, but that may not be the case? meaning, this setup may not work if the game is running in windows, but you're watching the filesystem in linux?

or, if that's off the mark - are you expecting it to immediately copy all blueprint `.xc` files?

**Comment by tsal** [comment]
also, v0.3.0 is released and should install now with `cargo install archbelt`; I'll be online for another hour or so, and will be spending some time on 0.4.0 tomorrow. if I get this fixed to your satisfaction during that time, I'll publish it as v0.3.1.
